services:
  jenkins:
    build: /Users/sseebald/code/nginx_demo/infra/
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - /Users/sseebald/code/tmp/jenkins_home:/var/jenkins_home
      - /Users/sseebald/code/nginx_demo/infra/jenkins_casc:/var/jenkins_home/casc_configs
    environment:
      - CASC_JENKINS_CONFIG=/var/jenkins_home/casc_configs
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false
 
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
