services:
  nginx-off-the-shelf:
    image: nginx:latest
    container_name: nginx_off_the_shelf
    ports:
      - "8081:80"

  nginx-chainguard:
    image: cgr.dev/chainguard/nginx
    container_name: nginx_chainguard
    ports:
      - "8082:80"
    volumes:
      - /Users/sseebald/code/nginx_demo/nginx.conf:/etc/nginx/nginx.conf:ro
      - /Users/sseebald/code/nginx_demo/html/index.html:/var/www/html/index.html:ro
      - /Users/sseebald/code/nginx_demo/html/run:/run/nginx
    user: "65532:65532"
